name: siakadumt
version: 1.0.0+1
publish_to: none
description: A new siakad UMT project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  carousel_slider: ^4.2.1

dev_dependencies: 
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
